### PR TITLE
Add some installation information

### PR DESCRIPTION
**Pull request by heavyrubberslave**
### Summary
Add some installation information to the README which is necessary to install the app over Xcode on the iPhone and get it up and running there.

* Change the Bundle Identifier to something unique in Xcode.
* Trust your own developer on your iDevice under "Settings -> General -> Profile -> (your iCloud account)"

### CODE REVIEW

**Comment by jacortinas** [comment]
@heavyrubberslave Thank you! First outside contribution! 😀 

This PR gets a thumbs up :+1: from me, going to get another review and we'll merge it today. Thank you again!

**Comment by philippt** [comment]
:+1:

**Comment by jacortinas** [comment]
@heavyrubberslave merged! Thank you again. 😄

**Comment by ErebusBat** [comment]
👍 

@heavyrubberslave you get 💯 internets!

**Pull request merged**
