### PR TITLE
Use a new unique bundle identifier and set the build version to 1.3.

### PR DESCRIPTION
**Pull request by jacortinas**
Hopefully if we don’t use `co.bitlove.FetLife` we can have developers all use the same bundle id. I’m not sure if it’s currently possible.

### CODE REVIEW

**Comment by jacortinas** [comment]
It's possible that with a new unique bundle identifier developers can use the same bundle id, and we can get better error tracking, but I'm not sure if it will work or not.

**Comment by jacortinas** [comment]
Has an effect on the solutions for #10 and #11.

**Comment by philippt** [comment]
:+1:

**Comment by reneklacan** [comment]
👍

**Pull request merged**
