### PR TITLE
Use in-app WebView vs. Safari Web View.

### PR DESCRIPTION
**Pull request by jacortinas**
Aesthetically the in-app web view looks really nice. Screenshots ~~coming soon~~ below.

### CODE REVIEW

**Comment by jacortinas** [comment]
|before|after|
|---|---|
|simulator screen shot apr 20 2016 3 41 07 pm|simulator screen shot apr 20 2016 3 41 46 pm|

@JohnBaku thoughts?

**Comment by JohnBaku** [comment]
@jacortinas I don't have a strong opinion either way... I do like that it's obvious you are opening up a URL to login so people know what's going on... my bigger concern is that the browser window does not close after authenticaton automatically so you are kind of left scratching your head wondering what's next.

**Comment by jacortinas** [comment]
@JohnBaku it should close immediately after authentication, if it doesn't it's a bug. 🐛  😅 

If after merging this PR it's something that can be replicated, I think it should definitely be given some time to determine the root cause.

**Comment by ErebusBat** [comment]
👍

**Comment by reneklacan** [comment]
👍

**Pull request merged**
