### PR TITLE
Make app icon more generic to reflect expanded scope of app.

### PR DESCRIPTION
**Pull request by jacortinas**
Trying out the logo, in a similar style to the modified chat bubble style. :grin: I think it looks pretty good, what does everyone else think?

Screenshot of the icon in a comment below. :point_down: 

/cc @JohnBaku

### CODE REVIEW

**Comment by jacortinas** [comment]
screen shot 2016-04-23 at 12 19 10 am

**Comment by reneklacan** [comment]
I like the icon, I don't like the fact that you can see borders of background (or is it normal on iOS?) 👍

**Comment by jacortinas** [comment]
The background of the icon has a gradient that from lighter to darker, is that what you mean?

**Comment by JohnBaku** [comment]
I like that we are switching it to the FetLife icon! One small thing... I have a funny feeling that icon you used is a bit off proportion-wise. I sent you a link to the original icon for you to just double check.

Thanks!

And if you want me to create the icon for you. Just hit me up.

**Comment by jacortinas** [comment]
screen shot 2016-04-25 at 8 47 44 am

@JohnBaku Icon has been adjusted, it should now have the correct proportions.

**Comment by jacortinas** [comment]
I think everyone is happy with the changes 😄 going ahead with merging this PR. :+1:

**Pull request merged**
