### PR TITLE
Update to Realm 1.0.0 and fix minor bugs

### PR DESCRIPTION
**Pull request by eebean2**
### Summary

Fully updated PODS
Updated code to compatibility with Realm 1.0.0
Updated minor code for relevancy
Resolved other minor bugs preventing app from launching

### Other Information

Swift.gitignore may be used if desired

### CODE REVIEW

**Comment by reneklacan** [comment]
👍 😍 Thank you!

**Comment by JohnBaku** [comment]
@jacortinas ?

**Comment by jacortinas** [comment]
@eebean2 Checking this out! I'm 99% sure this will be accepted. Thank you for your contribution. :bow:

**Comment by jacortinas** [comment]
@eebean2 The only thing I'm confused about is the `Swift.gitignore`, as far as I can tell it strips the project of a `.gitignore`, but I feel like I'm missing something. 😅

**Comment by eebean2** [comment]
When I cloned the project, it didn't include the '. gitignore' so I grabbed one from another project of mine and used it.

**Comment by eebean2** [comment]
Beyond changing the .gitignore, that is the only non-code item I think I changed, excluding updating pods, which were causing the bulk of the problem. But none of them were renamed.

**Comment by jacortinas** [comment]
:+1:

**Comment by jacortinas** [comment]
Thank you for your contribution @eebean2!

**Comment by eebean2** [comment]
No problem @jacortinas!

**Pull request merged**
